version: 2
jobs:
  build:
    docker:
      - image: gcr.io/istio-testing/website-builder:2018-08-30

    working_directory: ~/site

    steps:
      - checkout

      - run:
          name: Generating Site
          command: scripts/gen_site.sh "" -no_minify

      - run:
          name: Generating Helm repository
          command: |
            ./scripts/gen_helm_repo.sh
            cp -r ./charts ./public/charts

      - run:
          name: Running Linters
          command: scripts/lint_site.sh
